PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbp: <http://ja.dbpedia.org/property/>
select ?xlabel
where {
  ?x
    dbp:生月 ?birthMonth;
    dbp:生日 ?birthDay;
    rdfs:label ?xlabel.
  filter(
      month(now()) = ?birthMonth &&
      day(now()) = ?birthDay
  )
}
