select distinct
  ?prefix
  (count(distinct(?class)) as ?num)
  (group_concat(distinct ?class;SEPARATOR="|") as ?classes)
where {
  ?x a ?y.
  bind(
    "^(.+[^a-zA-Z_0-9-])([a-zA-Z_0-9-]*)$" as ?p
  )
  bind(
    replace(str(?y), ?p, "$1") as ?prefix
  )
  bind(
    replace(str(?y), ?p, "$2") as ?class
  )
}
group by ?prefix
order by desc(count(distinct(?class)))
